config/routes.rb
Rails.application.routes.draw do

  get 'stories/index'

  get 'followers/index'

  get 'followers/new'

  get 'followers/create'

  get 'followers/update'

  get 'followers/destroy'

  get 'followers/edit'

  get 'followers/show'

  resources :users
  
  resources :posts do
    resources :comments
  end

  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/story.rb
class Story
	attr_accessor :title, :url

	def initialize(title: title, url: url)
		@title=title
		@url=url
	end

	def self.get_mash_stories
		url='http://mashable.com/feed.json'
		response=JSON.load(RestClient.get(url))

		response["new"].map do |story|
			Story.new title: story["title"], url: story["link"]
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
def current_user
  	session[:user_id] ? User.find(session[:user_id]) :nil
  	# if session[:user_id]
  	# 	User.find(session[:user_id])
  	# else
  	# 	nil
  	# end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :show, :destroy]

def new
	@comment=Comment.new
end

def create
	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comment_params)
  	@comment.user = current_user
  	if @comment.save
    	redirect_to @post
  	else
    	flash.now[:danger] = "error"
	end
end

  def edit
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.user = current_user
  end

  def update
    @post=Post.find(params[:post_id])
    @comment.update(comment_params)
    redirect_to post_path(@post), notice: "Comment successfully updated."
  end

  def show
  end

  def destroy
    @post=Post.find(params[:post_id])
    @comment=@post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def set_comment
  	@comment=Comment.find(params[:id])
  end

  def comment_params
  	params.require(:comment).permit(:user_id, :post_id, :body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]

  def index
  	@post=Post.all
  end

  def new
  	if current_user
  		@post=Post.new
  	else
  		flash[:notice]="Please sign in first."
  		redirect_to signin_path
  	end
  end

  def create
  	@post=Post.create(post_params)
  	redirect_to @post, notice: "New post created."
  end

  def update
  	@post.update(post_params)
  	redirect_to @post, notice: "Post successfully updated."
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path, notice: "Post deleted."
  end

  def edit
  end

  def show
    @comment=Comment.new(:post=>@post)
  end

  private
  
  def set_post
  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:title, :body).merge(user_id: current_user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	@user=User.find_by(email: params[:email])
  	if @user and @user.password == params[:password]
  		flash[:notice]="Successfully signed in!"
  		session[:user_id]=@user.id
  		redirect_to @user
  	else
  		flash[:alert]="Something went wrong."
  		redirect_to root_path
  	end
end

  def destroy
  	session[:user_id]=nil
  	flash[:notice]="Logged out."
  	redirect_to root_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
  	@stories=Story.get_mash_stories
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def index
  	@users = User.all
  end

  def new
  	@user=User.new
  end

  def edit
  end

  def show
  end

  def create
  	@user = User.create(user_params)
  	redirect_to @user, notice: "New user created"
  end

  def destroy
  	@user.destroy
    session[:user_id]=nil
  	redirect_to users_path, notice: "User logged out and deleted."
  end

  def update
  	@user.update(user_params)
  	redirect_to @user, notice: "User susccessfully updated."
  end

  private

  def set_user
  	@user=User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :bio, :password, :age)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController<ApplicationController
	def index
		@message="Thanks for visiting Happy Blog!"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		session[:user_id] ? User.find(session[:user_id]) :nil
  	end
  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def display_post(post)
		result = link_to post.title, post_path(post)
		result<< " (written #{time_ago_in_words(post.created_at)} ago)"
		if current_user == post.user
			result<<" | "
			result << link_to('edit', edit_post_path(post))
			result << " | "
			result << link_to('delete', post_path(post), method: :delete,
		data: {confirm: "Are you sure?"})
		end
		result.html_safe
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |c| %>

	<%=c.label :body, 'Comment' %>
	<%=c.text_area :body %> <br/>

	<%=c.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%=render 'form'%>
<br/>
<%= link_to 'Cancel', posts_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Healthy Eats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
<h1>Food Blog</h1>
			<%=render 'share/login'%> <%= link_to 'Home', '/' %>
			| <%= link_to 'Posts', posts_path %>
			| <%= link_to 'New User?', new_user_path %>
</nav>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "alert alert-#{name}" %>
<% end %>
	


<%= yield %>
</div>
</div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

	<%=f.label :title %>
	<%=f.text_field :title %> <br/>

	<%=f.label :body%>
	<%=f.text_area :body%> <br/>

	<%=f.submit %>

<%end%>

app/views/posts/_post.html.erb
<%= content_tag :li, display_post(post)%>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%=render 'form'%>
<br/>
<%= link_to 'Cancel', posts_path %>

app/views/posts/index.html.erb
<h1>Welcome to Post Home</h1>

<ul style="list-style: none;">
		<%= render @post %>
</ul>

app/views/posts/new.html.erb
<h1>Write a New Post!</h1>
<%= render 'form' %>
<br />
<%= link_to 'cancel', posts_path %>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
	<p> <%=@post.body%> </p>
	
	<%=render '/comments/form' %>

	<h3> Comments <h3>
	
	<% @post.comments.each do |comment|%>
		<ul style="list-style: none;" >
				<%= comment.body %>		</ul>
				<% if current_user==comment.user %>
				<%= link_to 'Edit', edit_post_comment_path(@post, comment)%>
				<%= link_to 'Delete', [comment.post, comment],
               		:confirm => 'Are you sure?',
              		:method => :delete %>

	<% end%>
	<% end %>

app/views/share/_login.html.erb
<% if current_user %>
	<p>Hello <%=current_user.name %> |
	 <%= link_to 'sign out', logout_path, method: :delete %>
	 	|
	 <%= link_to 'new_post', new_post_path %>
	</p>
<% else %>
	<%= form_tag(signin_path, method: :post) do %>
		<form role="form" class="form-inline">
			<h4>Please Log In</h4>
			<div class="form-group">
				<%= label_tag :email %>
				<%= email_field_tag :email %>
			</div>
			<div class="form-group">
				<%= label_tag :password %>
				<%= password_field_tag :password %>
			</div>
				<%= submit_tag "login" %>
	</form>
	<% end %>
<% end %>

app/views/stories/index.html.erb
<h1>Stories</h1>

<ol>
	<%@stories.each do |story|%>
		<%= content_tag :li, link_to(story.title, story.url)%>
	<%end%>
</ol>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	
	<%=f.label :name %>
	<%=f.text_field :name %> <br/>

	<%=f.label :email %>
	<%=f.email_field :email%> <br/>

	<%=f.label :bio %>
	<%=f.text_area :bio%> <br/>

	<%=f.label :age %>
	<%=f.text_area :age%> <br/>

	<%=f.label :password %>
	<%=f.password_field :password%> <br/>

	<%=f.submit%>

<% end %>

app/views/users/edit.html.erb
<h1>Updating Your Profile</h1>
<%= render 'form' %> <br/>

<% link_to 'Cancel', users_path %>

app/views/users/index.html.erb
<h1>All Users</h1>

	<% @users.each do |user| %>
	<ul>
		<li> <%= link_to user.name, user_path(user) %> </li>
			<% if current_user==user %>
			<%= link_to 'edit', edit_user_path(user) %> | 
			<%= link_to 'delete', user_path(user), method: :delete,
				data: {confirm: "Are you sure?"} %>
			<%end%>
</ul>

<%end%>

app/views/users/new.html.erb
<h1>Welcome to Happy Blog!</h1>
<%= render 'form' %>
<br />

<%= link_to 'cancel', users_path %>

app/views/users/show.html.erb
<h1> Welcome <%=@user.name%></h1>

<p>(<%= @user.email %>) <%= @user.bio %></p>
	
	<% if current_user == @user %>
	<%= link_to 'Edit Profile', edit_user_path(@user) %>
	<%end%>

<h3><%= @user.name %>'s Posts</h3>

<ul>
	<% @user.posts.each do |post| %>
	<li><%= link_to post.title, post %></li>
	<% end %>
</ul>

<%= link_to 'Back', users_path %> 

app/views/welcome/index.html.erb
<h1>Welcome to Happy Blog</h1>

<h2> About</h2>